import "./globals.css";
import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import ToastProvider from "@/providers/toast-provider";
import Navbar from "@/components/navbar";

const inter = Urbanist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PPE App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastProvider />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
